--- 

info:
  description: Training configuration repo
  
---

spring:
  profiles: cloud

---  

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@eureka-serverv1.cfapps.io/eureka
